### PR TITLE
Add Ability to use an existing Application as the Hostbuilder host

### PR DESCRIPTION
**Pull request by ChrisPulman**
Extended WpfBuilder to include Application
add UseCurrentApplication extension method for defining Application
Added null check to ConfigureWpf to selectivly use existing Application

### CODE REVIEW

**Comment by Lakritzator** [comment]
Hey thanks.

Some small remarks, there are quite a lot of changes which distract from the thing you wanted to supply. I prefer PRs which only change what they want to introduce, no formatting and other changes which are not part of the main cause (side effects).

In the end, I managed to find the change and I think I understand it.
But what I fail to understand, is the use case for this.
You probably needed it, but can you explain why?

**Comment by ChrisPulman** [comment]
Basically it is to allow you to define all of the code that you have in the Main() and move it into the Application OnStartup override, this means there's no console window to hide.
I hadn't thought that I had changed the formatting much sorry, perhaps add a styleCop analyser to make it harder for people to provide incorrectly formatted check-ins.
I am using this small addition in a WPF project and it works nicely.

**Comment by Lakritzator** [comment]
So I finally had a bit more time looking at it, sorry got so much things going on...

I really enjoy getting PRs, and I'm glad you made one.
The basics of your change are sane and good!

Just some nit picking why I didn't merge yet, hope you can understand this.

You changed parts of the code which don't add anything for your feature. I meant the reformatting of the code, and especially the async/await statements you removed. I'm okay to discuss them, yeah it might add a bit of overhead but it also makes sure exceptions are handled, but these changes were not in the scope of what the PR was for.

Can you be so nice, to remove everything which doesn't have to do with the functionality to use an existing Application?

**Comment by ChrisPulman** [comment]
Sure no problem, I will revert to original and reapply the addition

**Comment by Lakritzator** [comment]
While adding code conventions etc. to this repository, I decided to make the "async/await" changes you had anyway, and consider it a "YAGNI" (you aint gonne need it) and using the "KISS" principle above solving potential issues right now.

In other words, I believe the suggestions you made are applied anyway.
You change is not, and you will have a lot of conflicts, sorry about that...
I guess it would be easier to recreated the PR... 🤷

**Pull request closed without merging**
