### PR TITLE
Feature -  Add Ability to use an existing WPF Application as the Host

### PR DESCRIPTION
**Pull request by ChrisPulman**
Recreated #26 
Extended WpfBuilder to include Application
add UseCurrentApplication extension method for defining Application
Added null check to ConfigureWpf to selectivly use existing Application

### CODE REVIEW

**Comment by Lakritzator** [comment]
I have no problem merging this, but I like to understand the use-case before I do.
As soon as I merge it, it's in the repo and I somehow need to support it, as I do not know what use-cases there are for it, I might forget about it.

**Comment by ChrisPulman** [comment]
In creating a demo, I found that there was a bunch of cross threading issues that were not there previously.
However the basis of this is that you can use a standard WPF template with App and use the App as the Application without needing to add Program and using Main as the application entry.
I will find out why the cross threading issues are occurring.

On a separate note I have found issues when the namespace and dll name contains the word Microsoft with some Microsoft DI scenario's. I can make a separate PR to remove the word Microsoft if you wish, keeping the Package names to be the same for continuity.

**Comment by Lakritzator** [comment]
> In creating a demo, I found that there was a bunch of cross threading issues that were not there previously. However the basis of this is that you can use a standard WPF template with App and use the App as the Application without needing to add Program and using Main as the application entry. I will find out why the cross threading issues are occurring.

I'll wait to merge this, as I do not like to have such issues. I can imagine that there are issues, as this project probably doesn't get the correct UI context.

> On a separate note I have found issues when the namespace and dll name contains the word Microsoft with some Microsoft DI scenario's. I can make a separate PR to remove the word Microsoft if you wish, keeping the Package names to be the same for continuity.

Can you explain what you mean with that? My namespaces do not start with Microsoft, so if there would be an issue, we might want to tackle this in the Microsoft DI libraries itself?

**Comment by ChrisPulman** [comment]
@Lakritzator  
Any thoughts on getting this merged?

**Review by Lakritzator — APPROVED** [review]

**Comment by Lakritzator** [comment]
I'm a bit occupied with Greenshot, so sorry for the delay.
Looks very good, and I almost pressed merge... but I expect some issues when I would like to merge #37 too...

**Comment by ChrisPulman** [comment]
> I'm a bit occupied with Greenshot, so sorry for the delay. Looks very good, and I almost pressed merge... but I expect some issues when I would like to merge #37 too...

I can try to see what impact #37 has and if anything needs to be added or changed to merge both PR's. I am currently working in Dubai so should get some spare time in the evenings.

**Comment by Lakritzator** [comment]
I had a quick look, and the conflict should be minimal (or even none), as the changes for the WinUI are in separate files.
It might be that something needs to be changed there, but I think it should not.

I will merge and we will solve anything that comes when merging that.

**Comment by Lakritzator** [comment]
Does this supersede #27?

**Comment by ChrisPulman** [comment]
> Does this supersede #27?

I think #27 has a few extra features I will take a look to see what the main things are and perhaps recreate anything useful due to the age of the PR it probably needs revisiting.

**Pull request merged**
