### PR TITLE
move off PackageIconUrl

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by Lakritzator** [comment]
That works? I couldn't find a solution last time I checked ... And the warning was annoying.
Thanks!

**Comment by Lakritzator** [comment]
I guess it doesn't work, while .ico is not supported.
No problem, I'll convert it to a png

**Comment by SimonCropp** [comment]
sorry. i had assumed if ico worked as a url it would work embedded

**Comment by Lakritzator** [comment]
No worries, your change motivated me to finally fix this.
I've got it fixed now.

**Pull request merged**
