### PR TITLE
Implement WinUI

### PR DESCRIPTION
**Pull request by AliveDevil**
For the samples following applies:
* > Requires [Project Reunion 0.8 stable sdk](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel)
* > Requires [Single Project MSIX-support package](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp)

As the regular implementation does not depend on WinUI (only the nuget package for references) I don't think this requires any knowledge of WinUI/Project Reunion/Windows App SDK

Implements #29

### CODE REVIEW

**Comment by Lakritzator** [comment]
I created a new branch (feature/WinUI), and targeted this PR to it, which allows us to play with it before putting it into master.

**Comment by Lakritzator** [comment]
Ok, cool, I will try it out as soon I as have some time.

**Comment by kevinchalet** [comment]
That would be awesome to see this PR merged ❤️‍🔥

**Comment by AliveDevil** [comment]
> That would be awesome to see this PR merged ❤️‍🔥

I’ll see that I get it up to date and working  next week.

**Pull request merged**
